apiVersion: v2
name: kafka-scada-parser
description: A Helm chart for pushing data from kafka topic to a CSV file at a specified location
type: application
version: 1.0.1

dependencies:
    - name: file-mover
      repository: "https://energinet-singularity.github.io/helm-registry/"
      version: 1.0.1
