# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

file-mover:
  podLabels:
    fm-dlr-parser: "S1"
  selectorLabels:
    fm-dlr-parser: "S1"
  folderMounts:
    input:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: kafka-scada-parser-pvc
    output:
      enabled: true
      volume:
        emptyDir: {}

replicaCount: 1

image:
  repository: ghcr.io/energinet-singularity/dlr-parser/energinet-singularity/dlr-parser
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

kafka:
  ip: ""
  topic: ""

file:
  path: ""
  name: ""

kafkascadaparserDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard
