# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/energinet-singularity/dlr-parser/energinet-singularity/dlr-parser
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.3"

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: kafka-scada-parser-pvc
    output:
      enabled: true
      volume:
        emptyDir: {}
  podLabels:
    fm-dlr-parser: "S1"
  selectorLabels:
    fm-dlr-parser: "S1"
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: dlr-fm-parser
                operator: In
                values:
                - S1

replicaCount: 1

podLabels:
  dlr-fm-parser: "S1"
selectorLabels:
  dlr-fm-parser: "S1"
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: fm-dlr-parser
              operator: In
              values:
              - S1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []

kafka:
  ip: ""
  topic: ""

file:
  path: ""
  name: ""

kafkascadaparserDataVolume:
  accessMode: ReadWriteOnce
  size: 1G
  storageClass: standard
