---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-scada-parser-pvc
spec:
  accessModes:
    - {{ .Values.kafka-scada-parserDataVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.kafka-scada-parserDataVolume.size }}
  storageClassName: {{ .Values.kafka-scada-parserDataVolume.storageClass }}
