---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-scada-parser-pvc
spec:
  accessModes:
    - {{ .Values.kafkascadaparserDataVolume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.kafkascadaparserDataVolume.size }}
  storageClassName: {{ .Values.kafkascadaparserDataVolume.storageClass }}
